___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Авторские права принадлежат Pierian Data</em></center>
<center><em>Для дополнительной информации посетите наш сайт <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# NumPy 

NumPy - это мощная библиотека Python для линейной алгебры. Почти все другие библиотеки в экосистеме <a href='https://pydata.org/'>PyData</a>  (pandas, scipy, scikit-learn и т.д.) используют внутри себя NumPy. А ещё, чуть позже, мы с помощью этой библиотеки сгенерим данные для наших примеров!

NumPy работает очень быстро, поскольку содержит ссылки на библиотеки, написанные на C. Более подробно почитать о том, почему лучше использовать массивы вместо списков, Вы можете в [этой статье на StackOverflow (англ.)](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Мы изучим только основы NumPy. Начнём с установки!

## *Замечание*: Инструкции по установке Numpy

### NumPy уже есть в Вашей среде environment! Мы ОЧЕНЬ рекомендуем Вам использовать те настройки, которые показаны в лекции по установке и настройке. Если Вы используете среду, которая предлагается в курсе, то у Вас всё должно быть хорошо!

_____
##### Для тех, кто не использует предлагаемую среду:

**Мы рекомендуем установить Python, используя дистрибутив Anaconda. В этом случае можно обеспечить наличие зависимых библиотек (таких как библиотеки линейной алгебры), используя команду conda install. Если у Вас есть Anaconda, то установите NumPy следующим образом - откройте командную строку или терминал, и введите следующую команду:**
    
    conda install numpy
    
    
**Если Вы по каким-то причинам не можете установить Anaconda, то можете посмотреть [официальную документацию Numpy, в которой приведены инструкции для различных вариантов установки.](https://www.scipy.org/install.html)**

_____

## Импортируем NumPy

После установки NumPy, Вы можете импортировать его как библиотеку:

In [1]:
import numpy as np

В NumPy есть много встроенных функций и возможностей. Мы не будем рассматривать их все, а рассмотрим только наиболее важные аспекты NumPy: векторы (vectors), массивы (arrays), матрицы (matrices) и генерация чисел. Начнём с массивов.

# Массивы NumPy

Мы будем часто использовать массивы NumPy на протяжении всего курса. Массивы NumPy бывают двух типов: векторы (vectors) и матрицы (matrices). Векторы - это строго одноразмерные массивы (1D), а матрицы - двумерные массивы (2D). Следует однако заметить, что матрица может состоять только из одной строки или только из одного столбца.

## Зачем использовать массивы Numpy? Почему нельзя просто использовать список?

Есть много причин, по которым массивы Numpy могут быть лучше "стандартного" списка List в Python.  
Наши основные причины следующие:
* Эффективное управление памятью
* Легко расширяется до N-размерных объектов
* Скорость вычислений для массивов numpy
* Возможность применять операции и функции сразу для всех элементов массива (broadcasting)
* Все библиотеки data science и машинного обучения, которые мы будем использовать, построены на основе Numpy


Начнём с рассмотрения различных способов создания массивов NumPy.

## Создание массивов NumPy на основе Объектов

### На основе списка Python

Мы можем сконвертировать список или "список списков" в массив:

In [2]:
my_list = [1,2,3, 4]
my_list

[1, 2, 3, 4]

In [7]:
type(my_list)

list

In [3]:
np.array(my_list)

array([1, 2, 3, 4])

In [9]:
type(my_list)

list

In [10]:
my_arr = np.array(my_list)
my_arr

array([1, 2, 3, 4])

In [11]:
type(my_arr)

numpy.ndarray

In [12]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
new_matrix = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

In [15]:
my_new_matrix = np.array(new_matrix)
my_new_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## Встроенные методы для создания списков

Существует много встроенных методов для генерации массивов.

### arange

Возвращает равноудалённые друг от друга значения в заданном интервале. [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [23]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [27]:
np.arange(0, 101, 20).reshape(3, 2)

array([[  0,  20],
       [ 40,  60],
       [ 80, 100]])

### zeros и ones - нули и единицы

Создание массивов из нулей или единиц. [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [29]:
np.zeros(3)

array([0., 0., 0.])

In [31]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.zeros((5, 2), order='F')

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Возвращает равноудалённые друг от друга числа в заданном интервале. [[документация (англ.)](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]  
Этот метод очень похож на arange, но если в arange мы указывали шаг между числами, то в linspace мы указываем количество чисел. Это особенно полезно для чисел float.

In [43]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [44]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Обратите внимание, что `.linspace()` *включает* верхнюю границу диапазона. Поэтому если, например,мы хотим  разделить интервал от 0 до 5 на 20 отрезков, то нужно указать количество чисел 21:</font>

In [46]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [47]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
np.linspace(0, 10, 10, endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [49]:
np.linspace(0, 10, 11, endpoint=False)

array([0.        , 0.90909091, 1.81818182, 2.72727273, 3.63636364,
       4.54545455, 5.45454545, 6.36363636, 7.27272727, 8.18181818,
       9.09090909])

In [53]:
np.linspace(0,5,21, retstep=True)

(array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
        2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ]),
 0.25)

In [55]:
len(np.linspace(0,5,21))

21

### eye

Создаёт единичную матрицу - единицы на главной диагонали, остальные нули [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [57]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
np.eye(4, k=-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

## Случайные числа (Random Numbers)
В Numpy есть много разных способов создавать массивы со случайными числами:

### rand
Создаёт массив указанной размерности, и заполняет его случайными числами с равномерным распределением вероятности на отрезке ``[0, 1)``. [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [16]:
np.random.rand(2)

array([0.37065108, 0.89813878])

In [69]:
np.random.rand(5,4)

array([[0.36729112, 0.40201157, 0.22881922, 0.08355818],
       [0.66003079, 0.53578784, 0.82662319, 0.98016876],
       [0.99035795, 0.18817718, 0.78429878, 0.55674883],
       [0.87643633, 0.20644745, 0.91654957, 0.03313479],
       [0.50068704, 0.65692996, 0.82356216, 0.59126738]])

### randn

Возвращает сэмпл (или сэмплы) из стандартного нормального распределения [σ = 1] в диапазоне от -1 до +1. В отличие от **rand** , в котором распределение равномерное, здесь более вероятны значения в середине диапазона (около нуля). [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [78]:
np.random.randn(2)

-1.1194704956012922

In [113]:
np.random.randn(5,5)

array([[ 1.31983423, -0.58458038,  1.01612225,  0.59246999,  0.13548117],
       [-0.09439077, -0.87508041,  1.20175204, -0.36624525, -0.64875298],
       [-0.35561886, -0.15676738,  0.74727573,  0.79305327,  0.57002189],
       [-1.03280278,  0.0664141 , -0.36530369,  0.74691322,  1.28828227],
       [-0.33313455, -0.76240181,  0.39709523,  0.7734761 , -2.77208376]])

### randint
Возвращает случайные целые числа в диапазоне от `low` (включительно) до `high` (не включая это значение).  [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [116]:
np.random.randint(1,100)

28

In [117]:
np.random.randint(1,100,10)

array([36, 72, 73, 42,  8, 92, 87, 45, 98, 82])

In [157]:
np.random.randint(1, [3, 5, 10])

array([1, 4, 8])

In [194]:
np.random.randint([[1, 2, 3, 4], [10, 10, 10, 10]], [[10], [20]], dtype='int64')

array([[ 5,  6,  7,  4],
       [10, 15, 13, 11]])

### seed
Эту функцию можно использовать для задания начальной точки генерации случайных чисел, чтобы можно было воспроизвести одни и те же "случайные" числа. [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [196]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [197]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [199]:
np.random.seed(42)
np.random.randint(10, 100, (2, 4))

array([[61, 24, 81, 70],
       [30, 92, 96, 84]])

In [202]:
np.random.seed(42)
np.random.randint(10, 100, (2, 4))

array([[61, 24, 81, 70],
       [30, 92, 96, 84]])

## Атрибуты и методы массивов

Давайте обсудим некоторые полезные атрибуты и методы для массивов:

In [204]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [205]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [206]:
ranarr

array([10, 23, 35, 39, 23,  2, 21,  1, 23, 43])

## Reshape
Возвращает массив с теми же данными, но с новой размерностью массива. [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [207]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [217]:
print(ranarr)
print(ranarr.reshape(5, 2))
print(ranarr.reshape(5, 2, order='A'))
ranarr.reshape(5, 2, order='F')

[10 23 35 39 23  2 21  1 23 43]
[[10 23]
 [35 39]
 [23  2]
 [21  1]
 [23 43]]
[[10 23]
 [35 39]
 [23  2]
 [21  1]
 [23 43]]


array([[10,  2],
       [23, 21],
       [35,  1],
       [39, 23],
       [23, 43]])

In [220]:
ranarr.reshape(2, -1)

array([[10, 23, 35, 39, 23],
       [ 2, 21,  1, 23, 43]])

In [223]:
ranarr.reshape(-1, 2)

array([[10, 23],
       [35, 39],
       [23,  2],
       [21,  1],
       [23, 43]])

### max, min, argmax, argmin

Это полезные методы для поиска максимального и минимального значения, а также их местоположения с помощью argmax и argmin

In [224]:
ranarr

array([10, 23, 35, 39, 23,  2, 21,  1, 23, 43])

In [225]:
ranarr.max()

43

In [227]:
ranarr.argmax()

9

In [226]:
ranarr.min()

1

In [228]:
ranarr.argmin()

7

## Shape

Shape - это атрибут массивов (не метод):  [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [232]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [233]:
# Вектор
arr.shape

(25,)

In [235]:
# Обратите внимание на два набора скобок
arr = arr.reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [236]:
arr.shape

(5, 5)

In [243]:
print(arr.reshape(1,25).shape)
arr.reshape(1,25)

(1, 25)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [245]:
print(arr.reshape(25).shape)
arr.reshape(25)

(25,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [246]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [247]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Вы можете также посмотреть тип данных объектов внутри массива: [[документация (англ.)](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [229]:
arr.dtype

dtype('int64')

In [230]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

# Отличная работа!