___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Авторские права принадлежат Pierian Data</em></center>
<center><em>Для дополнительной информации посетите наш сайт <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# Индексация массивов в NumPy

В этой лекции мы обсудим, как можно получить отдельные элементы или набор элементов из массива.

In [1]:
import numpy as np

In [18]:
# Создаём некоторый массив
arr = np.arange(0,11)

In [19]:
# Отображаем его
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Индексация с помощью скобок
Самый простой способ выбрать один или несколько элементов из массива выглядит так же, как и для списков python:

In [4]:
# Получить значение по указанному индексу
arr[9]

9

In [5]:
# Получить диапазон значений
arr[2:6]

array([2, 3, 4, 5])

In [7]:
# Получить диапазон значений
print(arr[0:5])
arr[:5]

[0 1 2 3 4]


array([0, 1, 2, 3, 4])

In [10]:
arr[2::2]

array([ 2,  4,  6,  8, 10])

## Broadcasting (широковещание, вещание, трансляция, бродкастинг)

В отличие от списков Python, массивы NumPy позволяют применить какую-нибудь операцию сразу для всех элементов массива. Например, если вы хотите для списка заменить первые 5 элементов на другое значение, то Вы должны указать новый список из 5 значений - так, чтобы новый список был такой же размерности. Для массивов NumPy это необязательно - Вы можете указать одно значение сразу для большого количества элементов:

In [20]:
# Присваиваем значение для диапазона индекса (Broadcasting)
# arr[0:5]=100
arr[:5] = 100
# Отображаем массив
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [26]:
# Сбрасываем массив обратно, через минуту скажем почему
arr = np.arange(0,11)

# Отображаем весь массив
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Важное замечание по поводу срезов (slices)
slice_of_arr = arr[0:6]

# Отображаем только срез
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Вносим изменения в срез
slice_of_arr[:]=99

# Снова отображаем срез
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Обратите внимание, что эти изменения были внесены и в исходный массив!

In [31]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Данные не копируются - это просто ссылка на исходный массив! Такой подход позволяет экономить память!

In [35]:
# Чтобы сделать копию, это нужно указать явно
arr_copy = arr.copy()

arr_copy[:6] = 100
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [36]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Индексация двумерных массивов (матриц)

Общий формат: **arr_2d[row][col]** или **arr_2d[row,col]**. Лучше использовать вариант с запятой, так более наглядно.

In [40]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

# Отображаем массив
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
arr_2d.shape

(3, 3)

In [45]:
# Индексация строки
arr_2d[-1]

array([35, 40, 45])

In [46]:
# Формат arr_2d[row][col] или arr_2d[row,col]

# Получаем отдельный элемент матрицы
arr_2d[1][0]

20

In [48]:
arr_2d[0, 2]

15

In [49]:
# Получаем отдельный элемент матрицы
arr_2d[1,0]

20

In [51]:
# Двумерный массив - срезы

# Форма (2,2) от верхнего правого угла
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [55]:
# Нижний ряд
arr_2d[2]

array([35, 40, 45])

In [57]:
# Нижний ряд
arr_2d[2,1:]

array([40, 45])

## Дополнительные материалы по индексации
Индексирование двумерной матрицы поначалу может выглядеть странно, особенно если двигаться с некоторым шагом. Попробуйте поискать в google изображения по ключевым словам *NumPy indexing* - так Вы сможете найти полезные картинки, похожие вот на эту:

<img src= 'numpy_indexing.png' width=500/> Источник изображения: http://www.scipy-lectures.org/intro/numpy/numpy.html

## Выбор элементов по условию (Conditional Selection)

Это очень важный приём работы с данными, который мы позднее ещё раз встретим в Pandas. Поэтому убедитесь, что Вы понимаете этот раздел блокнота!

Давайте вкратце посмотрим, как можно использовать скобки для выбора элементов, используя операторы сравнения.

In [58]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [60]:
bool_arr = arr>4

In [61]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [62]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [63]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Отличная работа!
